# Generated by Django 5.1.2 on 2024-11-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateTimeField(verbose_name='Data e Hora')),
                ('locale', models.CharField(max_length=255, verbose_name='Local')),
                ('is_active', models.BooleanField(default=False, verbose_name='Evento Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.event', verbose_name='Evento')),
            ],
            options={
                'unique_together': {('email', 'event')},
            },
        ),
    ]
